name: 'Specmatic Insights Build Reporter for Github Action'
description: 'A GitHub Action to report stats from the build to Specmatic Insights server'
branding:
  icon: 'check-square'
  color: 'purple'
inputs:
  specmatic-insights-host:
    description: 'URL of the Specmatic Insights server. Will default to https://insights.specmatic.in, if not specified'
    required: false
  specmatic-reports-dir:
    description: 'Path to the Specmatic reports directory. Will default to ./build/reports/specmatic, if not provided'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
