name: 'Specmatic Insights Build Reporter for Github Action'
description: 'A GitHub Action to report stats from the build to Specmatic Insights server'
branding:
  icon: 'check-square'
  color: 'purple'
inputs:
  specmatic-insights-host:
    description: 'URL of the Specmatic Insights server. Ex: https://insights.specmatic.in'
    required: true
  specmatic-reports-dir:
    description: 'Path to the Specmatic reports directory. Ex: ./build/reports/specmatic'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
